name: LookUpSilly
options:
  bundleIdPrefix: com.lookupsilly
  deploymentTarget:
    iOS: "26.0"
  defaultConfig: Debug
  developmentLanguage: en
  knownRegions:
    - en

packages:
  RevenueCat:
    url: https://github.com/RevenueCat/purchases-ios.git
    from: 5.41.0

targets:
  LookUpSilly:
    type: application
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - path: LookUpSilly
        excludes:
          - "**/*.md"
          - "**/Preview Content"
    resources:
      - path: LookUpSilly/Assets.xcassets
      - path: LookUpSilly/en.lproj
      - path: LookUpSilly/Configuration.storekit
    entitlements:
      path: LookUpSilly/LookUpSilly.entitlements
      properties:
        com.apple.developer.family-controls: true
        com.apple.developer.ubiquity-kvstore-identifier: $(AppIdentifierPrefix)$(CFBundleIdentifier)
        com.apple.developer.icloud-container-identifiers:
          - iCloud.$(CFBundleIdentifier)
        com.apple.developer.icloud-services:
          - CloudKit
          - CloudDocuments
    dependencies:
      - package: RevenueCat
        product: RevenueCat
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.lookupsilly.app
        DEVELOPMENT_TEAM: 7U8RP38YWZ
        CODE_SIGN_STYLE: Automatic
        SUPPORTS_MACCATALYST: false
        TARGETED_DEVICE_FAMILY: "1" # iPhone only
        SWIFT_VERSION: "6.0"
        IPHONEOS_DEPLOYMENT_TARGET: "26.0"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_USER_SCRIPT_SANDBOXING: YES
        SWIFT_EMIT_LOC_STRINGS: YES
      configs:
        Debug:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        Release:
          SWIFT_COMPILATION_MODE: wholemodule
    
    info:
      path: LookUpSilly/Info.plist
      properties:
        CFBundleDisplayName: Look Up, Silly!
        CFBundleName: Look Up, Silly!
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        LSRequiresIPhoneOS: true
        LSApplicationCategoryType: public.app-category.productivity
        LSApplicationSecondaryCategoryType: public.app-category.utilities
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UIUserInterfaceStyle: Dark
        NSFamilyControlsUsageDescription: Look Up, Silly! needs Screen Time access to block distracting apps and help you stay focused.

schemes:
  LookUpSilly:
    build:
      targets:
        LookUpSilly: all
    run:
      config: Debug
    test:
      config: Debug

